# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='service.proto',
    package='',
    syntax='proto3',
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\rservice.proto\"\x1e\n\nAskRequest\x12\x10\n\x08question\x18\x01 \x01(\t\"\x19\n\x08\x41skReply\x12\r\n\x05reply\x18\x01 \x01(\t\"\"\n\x0fSuccessResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"6\n\x11\x41\x64\x64\x43ommandRequest\x12\x0f\n\x07pattern\x18\x01 \x01(\t\x12\x10\n\x08template\x18\x02 \x01(\t2\\\n\x02\x41i\x12\x1f\n\x03\x61sk\x12\x0b.AskRequest\x1a\t.AskReply\"\x00\x12\x35\n\x0b\x61\x64\x64_command\x12\x12.AddCommandRequest\x1a\x10.SuccessResponse\"\x00\x62\x06proto3'
)

_ASKREQUEST = _descriptor.Descriptor(
    name='AskRequest',
    full_name='AskRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='question', full_name='AskRequest.question', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=17,
    serialized_end=47,
)

_ASKREPLY = _descriptor.Descriptor(
    name='AskReply',
    full_name='AskReply',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='reply', full_name='AskReply.reply', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=49,
    serialized_end=74,
)

_SUCCESSRESPONSE = _descriptor.Descriptor(
    name='SuccessResponse',
    full_name='SuccessResponse',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='success', full_name='SuccessResponse.success', index=0,
            number=1, type=8, cpp_type=7, label=1,
            has_default_value=False, default_value=False,
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=76,
    serialized_end=110,
)

_ADDCOMMANDREQUEST = _descriptor.Descriptor(
    name='AddCommandRequest',
    full_name='AddCommandRequest',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name='pattern', full_name='AddCommandRequest.pattern', index=0,
            number=1, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
        _descriptor.FieldDescriptor(
            name='template', full_name='AddCommandRequest.template', index=1,
            number=2, type=9, cpp_type=9, label=1,
            has_default_value=False, default_value=b"".decode('utf-8'),
            message_type=None, enum_type=None, containing_type=None,
            is_extension=False, extension_scope=None,
            serialized_options=None, file=DESCRIPTOR, create_key=_descriptor._internal_create_key),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    serialized_options=None,
    is_extendable=False,
    syntax='proto3',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=112,
    serialized_end=166,
)

DESCRIPTOR.message_types_by_name['AskRequest'] = _ASKREQUEST
DESCRIPTOR.message_types_by_name['AskReply'] = _ASKREPLY
DESCRIPTOR.message_types_by_name['SuccessResponse'] = _SUCCESSRESPONSE
DESCRIPTOR.message_types_by_name['AddCommandRequest'] = _ADDCOMMANDREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AskRequest = _reflection.GeneratedProtocolMessageType('AskRequest', (_message.Message,), {
    'DESCRIPTOR': _ASKREQUEST,
    '__module__': 'service_pb2'
    # @@protoc_insertion_point(class_scope:AskRequest)
})
_sym_db.RegisterMessage(AskRequest)

AskReply = _reflection.GeneratedProtocolMessageType('AskReply', (_message.Message,), {
    'DESCRIPTOR': _ASKREPLY,
    '__module__': 'service_pb2'
    # @@protoc_insertion_point(class_scope:AskReply)
})
_sym_db.RegisterMessage(AskReply)

SuccessResponse = _reflection.GeneratedProtocolMessageType('SuccessResponse', (_message.Message,), {
    'DESCRIPTOR': _SUCCESSRESPONSE,
    '__module__': 'service_pb2'
    # @@protoc_insertion_point(class_scope:SuccessResponse)
})
_sym_db.RegisterMessage(SuccessResponse)

AddCommandRequest = _reflection.GeneratedProtocolMessageType('AddCommandRequest', (_message.Message,), {
    'DESCRIPTOR': _ADDCOMMANDREQUEST,
    '__module__': 'service_pb2'
    # @@protoc_insertion_point(class_scope:AddCommandRequest)
})
_sym_db.RegisterMessage(AddCommandRequest)

_AI = _descriptor.ServiceDescriptor(
    name='Ai',
    full_name='Ai',
    file=DESCRIPTOR,
    index=0,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_start=168,
    serialized_end=260,
    methods=[
        _descriptor.MethodDescriptor(
            name='ask',
            full_name='Ai.ask',
            index=0,
            containing_service=None,
            input_type=_ASKREQUEST,
            output_type=_ASKREPLY,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.MethodDescriptor(
            name='add_command',
            full_name='Ai.add_command',
            index=1,
            containing_service=None,
            input_type=_ADDCOMMANDREQUEST,
            output_type=_SUCCESSRESPONSE,
            serialized_options=None,
            create_key=_descriptor._internal_create_key,
        ),
    ])
_sym_db.RegisterServiceDescriptor(_AI)

DESCRIPTOR.services_by_name['Ai'] = _AI

# @@protoc_insertion_point(module_scope)
